
package ch.admin.zas.wupispid.ws.managementservice._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpidManagementService", targetNamespace = "http://www.zas.admin.ch/wupispid/ws/managementService/1", wsdlLocation = "file:/Users/jostsa/github/first-jetty/src/main/java/com/smalljetty/wsdl/SpidManagementService.wsdl")
public class SpidManagementService
    extends Service
{

    private final static URL SPIDMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPIDMANAGEMENTSERVICE_EXCEPTION;
    private final static QName SPIDMANAGEMENTSERVICE_QNAME = new QName("http://www.zas.admin.ch/wupispid/ws/managementService/1", "SpidManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/jostsa/github/first-jetty/src/main/java/com/smalljetty/wsdl/SpidManagementService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPIDMANAGEMENTSERVICE_WSDL_LOCATION = url;
        SPIDMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public SpidManagementService() {
        super(__getWsdlLocation(), SPIDMANAGEMENTSERVICE_QNAME);
    }

    public SpidManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPIDMANAGEMENTSERVICE_QNAME, features);
    }

    public SpidManagementService(URL wsdlLocation) {
        super(wsdlLocation, SPIDMANAGEMENTSERVICE_QNAME);
    }

    public SpidManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPIDMANAGEMENTSERVICE_QNAME, features);
    }

    public SpidManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpidManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpidManagementServicePortTypeV1
     */
    @WebEndpoint(name = "SpidManagementServicePortV1")
    public SpidManagementServicePortTypeV1 getSpidManagementServicePortV1() {
        return super.getPort(new QName("http://www.zas.admin.ch/wupispid/ws/managementService/1", "SpidManagementServicePortV1"), SpidManagementServicePortTypeV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpidManagementServicePortTypeV1
     */
    @WebEndpoint(name = "SpidManagementServicePortV1")
    public SpidManagementServicePortTypeV1 getSpidManagementServicePortV1(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.zas.admin.ch/wupispid/ws/managementService/1", "SpidManagementServicePortV1"), SpidManagementServicePortTypeV1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPIDMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw SPIDMANAGEMENTSERVICE_EXCEPTION;
        }
        return SPIDMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
