
package ch.admin.zas.wupispid.ws.managementservice._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ch.ech.xmlns.ech_0213._1.Request;
import ch.ech.xmlns.ech_0213._1.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpidManagementServicePortTypeV1", targetNamespace = "http://www.zas.admin.ch/wupispid/ws/managementService/1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ch.ech.xmlns.ech_0213._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0135._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0021._7.ObjectFactory.class,
    ch.ech.xmlns.ech_0058._5.ObjectFactory.class,
    ch.ech.xmlns.ech_0011._8.ObjectFactory.class,
    ch.ech.xmlns.ech_0213_commons._1.ObjectFactory.class,
    ch.ech.xmlns.ech_0006._2.ObjectFactory.class,
    ch.ech.xmlns.ech_0007._5.ObjectFactory.class,
    ch.ech.xmlns.ech_0008._3.ObjectFactory.class,
    ch.ech.xmlns.ech_0010._5.ObjectFactory.class,
    ch.ech.xmlns.ech_0044._4.ObjectFactory.class
})
public interface SpidManagementServicePortTypeV1 {


    /**
     * 
     * @param body
     * @return
     *     returns ch.ech.xmlns.ech_0213._1.Response
     */
    @WebMethod(action = "http://www.zas.admin.ch")
    @WebResult(name = "response", targetNamespace = "http://www.ech.ch/xmlns/eCH-0213/1", partName = "body")
    public Response manageSpid(
        @WebParam(name = "request", targetNamespace = "http://www.ech.ch/xmlns/eCH-0213/1", partName = "body")
        Request body);

}
